modLoader = "javafml"
loaderVersion = "[2,)"
license = "${mod_license}"
issueTrackerURL = "${mod_repo_url}/issues"

[[mods]]
modId = "${mod_id}"
displayName = "${mod_name}"
version = "${mod_version}"
logoFile = "${mod_logo}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${supported_minecraft_versions}"
